# Generated by Django 4.2.3 on 2023-09-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEXT_number', models.CharField(max_length=10)),
                ('topic', models.TextField()),
                ('answer_options', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
