# Generated by Django 4.2.3 on 2023-10-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('questions_optional_number1', models.ManyToManyField(to='app01.englishoptionalnumber1')),
                ('questions_optional_number2', models.ManyToManyField(to='app01.englishoptionalnumber2')),
                ('questions_optional_number3', models.ManyToManyField(to='app01.englishoptionalnumber3')),
                ('questions_optional_number4', models.ManyToManyField(to='app01.englishoptionalnumber4')),
                ('questions_optional_number5', models.ManyToManyField(to='app01.englishoptionalnumber5')),
                ('questions_optionaltopic_number2', models.ManyToManyField(to='app01.optionaltopicnumber2')),
                ('questions_optionaltopic_number3', models.ManyToManyField(to='app01.optionaltopicnumber3')),
                ('questions_optionaltopic_number5', models.ManyToManyField(to='app01.optionaltopicnumber5')),
            ],
        ),
    ]
