# Generated by Django 4.2.5 on 2023-10-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_quizquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Academic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.TextField()),
                ("optionA", models.TextField()),
                ("optionB", models.TextField()),
                ("optionC", models.TextField()),
                ("optionD", models.TextField()),
                ("answer", models.CharField(max_length=10)),
                ("year", models.CharField(max_length=10)),
                ("topic_number", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="QuizQuestion",
        ),
    ]
