# Generated by Django 4.2.3 on 2023-10-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_academic_delete_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=40, unique=True, verbose_name='題目')),
                ('time', models.IntegerField(help_text='分鐘', verbose_name='考試時長')),
                ('pid', models.ManyToManyField(to='app01.academic')),
            ],
        ),
    ]
