# Generated by Django 4.2.3 on 2023-10-30 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_student_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_scores',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
