# Generated by Django 4.2.3 on 2023-10-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_student_scores_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_scores',
            name='user',
        ),
    ]
