# Generated by Django 4.2.3 on 2023-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_testpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(verbose_name='成績')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='考試時間')),
            ],
        ),
    ]
